using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace LibLCV {

    public class LCVConfig {
        public GTAConfig GTA { get; set; } = new();
        public MMConfig ModestMenu { get; set; } = new();
        public PrivateLobbyConfig PrivateLobby { get; set; } = new();
        public CommandLineConfig CommandLine { get; set; } = new();
    }

    public class GTAConfig {
        public string Path { get; set; } = string.Empty;
        public GTALaunchType LaunchType { get; set; } = GTALaunchType.Epic;
        public int EmptyLobbyFreezeTimeMS { get; set; } = 10000;
    }

    public class MMConfig {
        public string Path { get; set; } = string.Empty;
    }

    public class PrivateLobbyConfig {
        public bool Enabled { get; set; } = false;
        public string Key { get; set; } = string.Empty;
        public bool AutoFindKey { get; set; } = true;
        public bool AutoDetectEnabled { get; set; } = true;
        public string BaseFilePath { get; set; } = @"data\startup.meta.base";
    }

    public class CommandLineConfig {
        public bool Enabled { get; set; } = false;
        public bool AutoFindSettings { get; set; } = true;
        public bool AutoDetectEnabled { get; set; } = true;
        public List<CLFlagItem> FlagItems { get; set; } = new();
        public List<CLIntItem> IntItems { get; set; } = new();
        public List<CLDoubleItem> DoubleItems { get; set; } = new();
        public List<CLSelectItem> SelectItems { get; set; } = new();
        public int EnabledCount() => FlagItems.Count(c => c.IsSet) + IntItems.Count(c => c.IsSet) + DoubleItems.Count(c => c.IsSet) + SelectItems.Count(c => c.IsSet);
        public List<ICLItem> EnabledItems() {
            List<ICLItem> items = new();
            foreach(CLFlagItem clItem in FlagItems) if(clItem.IsSet) items.Add(clItem);
            foreach(CLIntItem clItem in IntItems) if(clItem.IsSet) items.Add(clItem);
            foreach(CLDoubleItem clItem in DoubleItems) if(clItem.IsSet) items.Add(clItem);
            foreach(CLSelectItem clItem in SelectItems) if(clItem.IsSet) items.Add(clItem);
            return items;
        }
    }

    public static class CommandLineConfigDefaults {
        public static List<CLFlagItem> FlagItems { get; set; } = new() {
            new CLFlagItem() { Name = "verify", Description = "Check game installation for problems and repair any issues found. Disc and non-Steam digital versions only.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "safemode", Description = "Start with minimum settings without saving them.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "ignoreprofile", Description = "Ignore the current profile settings.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "ignoreDifferentVideoCard", Description = "Don’t reset settings with a new graphics card.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "useMinimumSettings", Description = "Reset settings to the minimum.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "UseAutoSettings", Description = "Use automatically generated settings.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "DX10", Description = "Force 10.0 feature set.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "DX10_1", Description = "Force 10.1 feature set.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "DX11", Description = "Force 11.0 feature set.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "noChunkedDownload", Description = "Forces patches to be downloaded all at once instead of in chunks.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "mouseexclusive", Description = "Game uses mouse exclusively.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "disallowResizeWindow", Description = "Do Not allow the window to be resized.", Category = "Troubleshooting" },
            new CLFlagItem() { Name = "benchmark", Description = "Start the benchmark test from the command line.", Category = "Benchmarking" },
            new CLFlagItem() { Name = "benchmarkFrameTimes", Description = "Optionally output the individual frame times from the benchmark.", Category = "Benchmarking" },
            new CLFlagItem() { Name = "benchmarknoaudio", Description = "Disable audio processing for graphics benchmark purposes.", Category = "Benchmarking" },
            new CLFlagItem() { Name = "StraightIntoFreemode", Description = "If present the game will automatically launch into the multiplayer game in freemode.", Category = "Game Preferences" },
            new CLFlagItem() { Name = "goStraightToMP", Description = "Jump straight to MP while loading.", Category = "Game Preferences" },
            new CLFlagItem() { Name = "scOfflineOnly", Description = "Launch the game in offline mode.", Category = "Game Preferences" },
            new CLFlagItem() { Name = "windowed", Description = "Force windowed mode.", Category = "Window Preferences" },
            new CLFlagItem() { Name = "fullscreen", Description = "Force fullscreen mode.", Category = "Window Preferences" },
            new CLFlagItem() { Name = "borderless", Description = "Set main window to be borderless.", Category = "Window Preferences" },
            new CLFlagItem() { Name = "disableHyperthreading", Description = "Do not count hyperthreaded cores as real ones to create tasks on.", Category = "Graphics" },
            new CLFlagItem() { Name = "noInGameDOF", Description = "Disable In-game DOF effects.", Category = "Graphics" },
            new CLFlagItem() { Name = "hdr", Description = "Set the whole rendering pipeline to 16-bit.", Category = "Graphics" },
            new CLFlagItem() { Name = "noquattransform", Description = "Don’t use quaternion transforms for placed entities.", Category = "Graphics" },
            new CLFlagItem() { Name = "SSA", Description = "Enable SSA.", Category = "Graphics" },
            new CLFlagItem() { Name = "HDStreamingInFlight", Description = "Enable HD streaming while in flight.", Category = "Graphics" },
        };
        public static List<CLIntItem> IntItems { get; set; } = new() {
            new CLIntItem() { Name = "GPUCount", Description = "Manual override GPU Count.", Category = "Benchmarking", Value = 1 },
            new CLIntItem() { Name = "adapter", Description = "Use the specified screen adapter number (zero-based).", Category = "Benchmarking", Value = 1 },
            new CLIntItem() { Name = "benchmarkIterations", Description = "Specifies the number of iterations for the benchmark to run.", Category = "Benchmarking", Value = 1, MinValue = 1 },
            new CLIntItem() { Name = "benchmarkPass", Description = "Specifies when an individual benchmark scene test should be done, and which test it should be.", Category = "Benchmarking", Value = 1, MinValue = 1 },
            new CLIntItem() { Name = "width", Description = "Set width of main render window (default is 640).", Category = "Window Preferences", Value = 640 },
            new CLIntItem() { Name = "height", Description = "Set height of main render window (default is 480).", Category = "Window Preferences", Value = 480 },
            new CLIntItem() { Name = "anisotropicQualityLevel", Description = "Set anisotropic filter quality level (0-16).", Category = "Graphics", MinValue = 0, MaxValue = 16 },
            new CLIntItem() { Name = "fogVolumes", Description = "Enable lights volumetric effects in foggy weather (0-1, unsure whether the value is necessary).", Category = "Graphics", MinValue = 0, MaxValue = 1 },
            new CLIntItem() { Name = "fxaa", Description = "Set FXAA quality (0-3). Leftover code, does not work, everything except 1 disables FXAA.", Category = "Graphics", MinValue = 0, MaxValue = 3 },
            new CLIntItem() { Name = "frameLimit", Description = "Number of vertical synchronizations to limit game to.", Category = "Graphics", Value = 144, MaxValue = 999 },
            new CLIntItem() { Name = "grassQuality", Description = "Set grass quality (0-5).", Category = "Graphics", MaxValue = 5 },
            new CLIntItem() { Name = "shadowSoftness", Description = "Selects between linear, rpdb, box 4x4, soft 16 (0-3).", Category = "Graphics", MaxValue = 3 },
            new CLIntItem() { Name = "particleQuality", Description = "Set particle quality (0-2).", Category = "Graphics", MaxValue = 2 },
            new CLIntItem() { Name = "particleShadows", Description = "Enable particle shadows (0-1).", Category = "Graphics", MaxValue = 1 },
            new CLIntItem() { Name = "postFX", Description = "Set postFX quality (0-3).", Category = "Graphics", MaxValue = 3 },
            new CLIntItem() { Name = "reflectionBlur", Description = "Enable reflection map blur (0-1).", Category = "Graphics", MaxValue = 1 },
            new CLIntItem() { Name = "reflectionQuality", Description = "Set reflection quality (0-3).", Category = "Graphics", MaxValue = 3 },
            new CLIntItem() { Name = "SSAO", Description = "Set SSAO quality (0-2).", Category = "Graphics", MaxValue = 2 },
            new CLIntItem() { Name = "shaderQuality", Description = "Set shader quality (0-2).", Category = "Graphics", MaxValue = 2 },
            new CLIntItem() { Name = "shadowLongShadows", Description = "Enable shadow rendering for dusk and dawn (0-1).", Category = "Graphics", MaxValue = 1 },
            new CLIntItem() { Name = "shadowQuality", Description = "Set shadow quality (0-3).", Category = "Graphics", MaxValue = 3, Value = 1 },
            new CLIntItem() { Name = "tessellation", Description = "Set tessellation on or off (or quality) (0-3).", Category = "Graphics", MaxValue = 3 },
            new CLIntItem() { Name = "textureQuality", Description = "Set texture quality (0-2).", Category = "Graphics", MaxValue = 2 },
            new CLIntItem() { Name = "txaa", Description = "Enable NVIDIA TXAA (0-1). Can only be enabled when MSAA ist at least 2x.", Category = "Graphics", MaxValue = 1 },
            new CLIntItem() { Name = "waterQuality", Description = "Set water quality (0-2).", Category = "Graphics", MaxValue = 2 },
        };
        public static List<CLDoubleItem> DoubleItems { get; set; } = new() {
            new CLDoubleItem() { Name = "cityDensity", Description = "Control city density (0.0-1.0).", Category = "Game Preferences", MaxValue = 1.0 },
            new CLDoubleItem() { Name = "lodScale", Description = "Set LOD Distance level (0.0-1.0).", Category = "Graphics", MaxValue = 1.0 },
            new CLDoubleItem() { Name = "pedLodBias", Description = "Set LOD Distance bias for pedestrians (0.0-1.0f).", Category = "Graphics", MaxValue = 1.0 },
            new CLDoubleItem() { Name = "vehicleLodBias", Description = "Set LOD Distance bias for vehicles (0.0-1.0f).", Category = "Graphics", MaxValue = 1.0 },
        };
        public static List<CLSelectItem> SelectItems { get; set; } = new() {
            new CLSelectItem() { Name = "multiSample", Description = "Number of multisamples (1, 2, 4, 8, or 16).", Category = "Graphics", Options = {
                new string[2]{"1",""},
                new string[2]{"2",""},
                new string[2]{"4",""},
                new string[2]{"8",""},
                new string[2]{"16",""},
            }},
            new CLSelectItem() { Name = "uilanguage", Description = "Set the in-game language.", Category = "Localization", Options = new() {
                new string[2]{ "american", "American English" },
                new string[2]{ "french", "French" },
                new string[2]{ "german", "German" },
                new string[2]{ "italian", "Italian" },
                new string[2]{ "spanish", "Spanish" },
                new string[2]{ "portuguese", "Portugese" },
                new string[2]{ "polish", "Polish" },
                new string[2]{ "russian", "Russian" },
                new string[2]{ "korean", "Korean" },
                new string[2]{ "chinese", "Chinese Traditional" },
                new string[2]{ "chinesesimp", "Chinese Simplified" },
                new string[2]{ "japanese", "Japanese" },
                new string[2]{ "mexican", "Mexican Spanish" },
            }},
            new CLSelectItem() { Name = "keyboardLocal", Description = "Sets the keyboard layout to the specified region.", Category = "Localization", SelectedIndex = 50, Options = new() {
                new string[2]{"0436","Afrikaans - South Africa"},
                new string[2]{"041c","Albanian - Albania"},
                new string[2]{"0484","Alsatian"},
                new string[2]{"045e","Amharic - Ethiopia"},
                new string[2]{"0401","Arabic - Saudi Arabia"},
                new string[2]{"1401","Arabic - Algeria"},
                new string[2]{"3c01","Arabic - Bahrain"},
                new string[2]{"0c01","Arabic - Egypt"},
                new string[2]{"0801","Arabic - Iraq"},
                new string[2]{"2c01","Arabic - Jordan"},
                new string[2]{"3401","Arabic - Kuwait"},
                new string[2]{"3001","Arabic - Lebanon"},
                new string[2]{"1001","Arabic - Libya"},
                new string[2]{"1801","Arabic - Morocco"},
                new string[2]{"2001","Arabic - Oman"},
                new string[2]{"4001","Arabic - Qatar"},
                new string[2]{"2801","Arabic - Syria"},
                new string[2]{"1c01","Arabic - Tunisia"},
                new string[2]{"3801","Arabic - U.A.E."},
                new string[2]{"2401","Arabic - Yemen"},
                new string[2]{"042b","Armenian - Armenia"},
                new string[2]{"044d","Assamese"},
                new string[2]{"082c","Azeri (Cyrillic)"},
                new string[2]{"042c","Azeri (Latin)"},
                new string[2]{"046d","Bashkir"},
                new string[2]{"042d","Basque"},
                new string[2]{"0423","Belarusian"},
                new string[2]{"0445","Bengali (India)"},
                new string[2]{"0845","Bengali (Bangladesh)"},
                new string[2]{"141A","Bosnian (Bosnia/Herzegovina)"},
                new string[2]{"047e","Breton"},
                new string[2]{"0402","Bulgarian"},
                new string[2]{"0455","Burmese"},
                new string[2]{"0403","Catalan"},
                new string[2]{"045c","Cherokee - United States"},
                new string[2]{"0804","Chinese - People's Republic of China"},
                new string[2]{"1004","Chinese - Singapore"},
                new string[2]{"0404","Chinese - Taiwan"},
                new string[2]{"0c04","Chinese - Hong Kong SAR"},
                new string[2]{"1404","Chinese - Macao SAR"},
                new string[2]{"0483","Corsican"},
                new string[2]{"041a","Croatian"},
                new string[2]{"101a","Croatian (Bosnia/Herzegovina)"},
                new string[2]{"0405","Czech"},
                new string[2]{"0406","Danish"},
                new string[2]{"048c","Dari"},
                new string[2]{"0465","Divehi"},
                new string[2]{"0413","Dutch - Netherlands"},
                new string[2]{"0813","Dutch - Belgium"},
                new string[2]{"0466","Edo"},
                new string[2]{"0409","English - United States"},
                new string[2]{"0809","English - United Kingdom"},
                new string[2]{"0c09","English - Australia"},
                new string[2]{"2809","English - Belize"},
                new string[2]{"1009","English - Canada"},
                new string[2]{"2409","English - Caribbean"},
                new string[2]{"3c09","English - Hong Kong SAR"},
                new string[2]{"4009","English - India"},
                new string[2]{"3809","English - Indonesia"},
                new string[2]{"1809","English - Ireland"},
                new string[2]{"2009","English - Jamaica"},
                new string[2]{"4409","English - Malaysia"},
                new string[2]{"1409","English - New Zealand"},
                new string[2]{"3409","English - Philippines"},
                new string[2]{"4809","English - Singapore"},
                new string[2]{"1c09","English - South Africa"},
                new string[2]{"2c09","English - Trinidad"},
                new string[2]{"3009","English - Zimbabwe"},
                new string[2]{"0425","Estonian"},
                new string[2]{"0438","Faroese"},
                new string[2]{"0429","Farsi"},
                new string[2]{"0464","Filipino"},
                new string[2]{"040b","Finnish"},
                new string[2]{"040c","French - France"},
                new string[2]{"080c","French - Belgium"},
                new string[2]{"2c0c","French - Cameroon"},
                new string[2]{"0c0c","French - Canada"},
                new string[2]{"240c","French - Democratic Rep. of Congo"},
                new string[2]{"300c","French - Cote d'Ivoire"},
                new string[2]{"3c0c","French - Haiti"},
                new string[2]{"140c","French - Luxembourg"},
                new string[2]{"340c","French - Mali"},
                new string[2]{"180c","French - Monaco"},
                new string[2]{"380c","French - Morocco"},
                new string[2]{"e40c","French - North Africa"},
                new string[2]{"200c","French - Reunion"},
                new string[2]{"280c","French - Senegal"},
                new string[2]{"100c","French - Switzerland"},
                new string[2]{"1c0c","French - West Indies"},
                new string[2]{"0462","Frisian - Netherlands"},
                new string[2]{"0467","Fulfulde - Nigeria"},
                new string[2]{"042f","FYRO Macedonian"},
                new string[2]{"0456","Galician"},
                new string[2]{"0437","Georgian"},
                new string[2]{"0407","German - Germany"},
                new string[2]{"0c07","German - Austria"},
                new string[2]{"1407","German - Liechtenstein"},
                new string[2]{"1007","German - Luxembourg"},
                new string[2]{"0807","German - Switzerland"},
                new string[2]{"0408","Greek"},
                new string[2]{"046f","Greenlandic"},
                new string[2]{"0474","Guarani - Paraguay"},
                new string[2]{"0447","Gujarati"},
                new string[2]{"0468","Hausa - Nigeria"},
                new string[2]{"0475","Hawaiian - United States"},
                new string[2]{"040d","Hebrew"},
                new string[2]{"0439","Hindi"},
                new string[2]{"040e","Hungarian"},
                new string[2]{"0469","Ibibio - Nigeria"},
                new string[2]{"040f","Icelandic"},
                new string[2]{"0470","Igbo - Nigeria"},
                new string[2]{"0421","Indonesian"},
                new string[2]{"045d","Inuktitut"},
                new string[2]{"083c","Irish"},
                new string[2]{"0410","Italian - Italy"},
                new string[2]{"0810","Italian - Switzerland"},
                new string[2]{"0411","Japanese"},
                new string[2]{"0486","K'iche"},
                new string[2]{"044b","Kannada"},
                new string[2]{"0471","Kanuri - Nigeria"},
                new string[2]{"0860","Kashmiri"},
                new string[2]{"0460","Kashmiri (Arabic)"},
                new string[2]{"043f","Kazakh"},
                new string[2]{"0453","Khmer"},
                new string[2]{"0487","Kinyarwanda"},
                new string[2]{"0457","Konkani"},
                new string[2]{"0412","Korean"},
                new string[2]{"0440","Kyrgyz (Cyrillic)"},
                new string[2]{"0454","Lao"},
                new string[2]{"0476","Latin"},
                new string[2]{"0426","Latvian"},
                new string[2]{"0427","Lithuanian"},
                new string[2]{"046e","Luxembourgish"},
                new string[2]{"043e","Malay - Malaysia"},
                new string[2]{"083e","Malay - Brunei Darussalam"},
                new string[2]{"044c","Malayalam"},
                new string[2]{"043a","Maltese"},
                new string[2]{"0458","Manipuri"},
                new string[2]{"0481","Maori - New Zealand"},
                new string[2]{"0471","Mapudungun"},
                new string[2]{"044e","Marathi"},
                new string[2]{"047c","Mohawk"},
                new string[2]{"0450","Mongolian (Cyrillic)"},
                new string[2]{"0850","Mongolian (Mongolian)"},
                new string[2]{"0461","Nepali"},
                new string[2]{"0861","Nepali - India"},
                new string[2]{"0414","Norwegian (BokmÃ¥l)"},
                new string[2]{"0814","Norwegian (Nynorsk)"},
                new string[2]{"0482","Occitan"},
                new string[2]{"0448","Oriya"},
                new string[2]{"0472","Oromo"},
                new string[2]{"0479","Papiamentu"},
                new string[2]{"0463","Pashto"},
                new string[2]{"0415","Polish"},
                new string[2]{"0416","Portuguese - Brazil"},
                new string[2]{"0816","Portuguese - Portugal"},
                new string[2]{"0446","Punjabi"},
                new string[2]{"0846","Punjabi (Pakistan)"},
                new string[2]{"046B","Quecha - Bolivia"},
                new string[2]{"086B","Quecha - Ecuador"},
                new string[2]{"0C6B","Quecha - Peru"},
                new string[2]{"0417","Rhaeto-Romanic"},
                new string[2]{"0418","Romanian"},
                new string[2]{"0818","Romanian - Moldava"},
                new string[2]{"0419","Russian"},
                new string[2]{"0819","Russian - Moldava"},
                new string[2]{"043b","Sami (Lappish)"},
                new string[2]{"044f","Sanskrit"},
                new string[2]{"043c","Scottish Gaelic"},
                new string[2]{"046c","Sepedi"},
                new string[2]{"0c1a","Serbian (Cyrillic)"},
                new string[2]{"081a","Serbian (Latin)"},
                new string[2]{"0459","Sindhi - India"},
                new string[2]{"0859","Sindhi - Pakistan"},
                new string[2]{"045b","Sinhalese - Sri Lanka"},
                new string[2]{"041b","Slovak"},
                new string[2]{"0424","Slovenian"},
                new string[2]{"0477","Somali"},
                new string[2]{"042e","Sorbian"},
                new string[2]{"0c0a","Spanish - Spain (Modern Sort)"},
                new string[2]{"040a","Spanish - Spain (Traditional Sort)"},
                new string[2]{"2c0a","Spanish - Argentina"},
                new string[2]{"400a","Spanish - Bolivia"},
                new string[2]{"340a","Spanish - Chile"},
                new string[2]{"240a","Spanish - Colombia"},
                new string[2]{"140a","Spanish - Costa Rica"},
                new string[2]{"1c0a","Spanish - Dominican Republic"},
                new string[2]{"300a","Spanish - Ecuador"},
                new string[2]{"440a","Spanish - El Salvador"},
                new string[2]{"100a","Spanish - Guatemala"},
                new string[2]{"480a","Spanish - Honduras"},
                new string[2]{"580a","Spanish - Latin America"},
                new string[2]{"080a","Spanish - Mexico"},
                new string[2]{"4c0a","Spanish - Nicaragua"},
                new string[2]{"180a","Spanish - Panama"},
                new string[2]{"3c0a","Spanish - Paraguay"},
                new string[2]{"280a","Spanish - Peru"},
                new string[2]{"500a","Spanish - Puerto Rico"},
                new string[2]{"540a","Spanish - United States"},
                new string[2]{"380a","Spanish - Uruguay"},
                new string[2]{"200a","Spanish - Venezuela"},
                new string[2]{"0430","Sutu"},
                new string[2]{"0441","Swahili"},
                new string[2]{"041d","Swedish"},
                new string[2]{"081d","Swedish - Finland"},
                new string[2]{"045a","Syriac"},
                new string[2]{"0428","Tajik"},
                new string[2]{"045f","Tamazight (Arabic)"},
                new string[2]{"085f","Tamazight (Latin)"},
                new string[2]{"0449","Tamil"},
                new string[2]{"0444","Tatar"},
                new string[2]{"044a","Telugu"},
                new string[2]{"041e","Thai"},
                new string[2]{"0851","Tibetan - Bhutan"},
                new string[2]{"0451","Tibetan - People's Republic of China"},
                new string[2]{"0873","Tigrigna - Eritrea"},
                new string[2]{"0473","Tigrigna - Ethiopia"},
                new string[2]{"0431","Tsonga"},
                new string[2]{"0432","Tswana"},
                new string[2]{"041f","Turkish"},
                new string[2]{"0442","Turkmen"},
                new string[2]{"0480","Uighur - China"},
                new string[2]{"0422","Ukrainian"},
                new string[2]{"0420","Urdu"},
                new string[2]{"0820","Urdu - India"},
                new string[2]{"0843","Uzbek (Cyrillic)"},
                new string[2]{"0443","Uzbek (Latin)"},
                new string[2]{"0433","Venda"},
                new string[2]{"042a","Vietnamese"},
                new string[2]{"0452","Welsh"},
                new string[2]{"0488","Wolof"},
                new string[2]{"0434","Xhosa"},
                new string[2]{"0485","Yakut"},
                new string[2]{"0478","Yi"},
                new string[2]{"043d","Yiddish"},
                new string[2]{"046a","Yoruba"},
                new string[2]{"0435","Zulu"},
            }},
        };
    }
}
